language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: SrYNrt9vsKq768RSJMsViqkJSQwwoR95XuBO1tjV4mpNQrbiXWiDau7+t6Thg5usxK4xCCSMDN8NK9yfIG/NayI3OiAy+MP1VPt39eJExUJ2+dE3um4/VlYfTrPu6AHmTPdNpqIadvajtNcbAy3VcxR6MD2If4HJ83JDIeDFrYr7jdfZq2prykMPaqBSXVGJSXANLrKgzkpWxUXCg3Rl6Sn/+Q9gbcoTgfw4GXTJodgFQ3fpXdCL7FEUI99yN0uBoP7edz9nKvK9YF8TjcxVhtSfAlwbvvncyDP4mdOsqcP26Ua2CalK5em8mw+mouim/c4mMK6qVqmyTe06FRcdqFHM7UjJLM65MEASFen1AhwlCEmq0fVIextQDvTs8s7Cr0+r5xYC8YWXss5ISDow4GQonsmcMAO9D/VFgINo5++1nIk9xCUc9iOrGWF6JaaeuE+CXDZ1eA1T5/O1K65pSKVxgqehRAQVJ6/avjRXhEV658mWWBGOK8ikniZpCemOvF/l+TaQhFMjN9enmZOt3pDFF/FyjhdXknRakdCu/ftDCiLiKQw23fE/6G3cQWhfv7gFwVTi0SnJRI4GKzxeNlJf1XcjmwcqGGwcZ4Z2wkAzKHwf9Xjn6JIFCMrP1j2lqEgRj6Qnwl3zEQIdnkGCxSiZIFdtnHcSTcEGVJtWjqg=
  app: enigmatic-refuge-40089
  on:
    repo: ispoljari/blog-app-ci
