language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: d1+5ag115ihAKQlagyhC1CVu1SLRnT8VDoaV2dVcCjDVFDlUlZGEUbikaeNNFbfXUtK9m/HSzN2FVUn5MnxsHK+1E43EYen/S2r3b7KjaL/59wJezGIjtiboecXGQdTxTB2zE6iCVg71bcQcJkx5nxX+bABYa/LXbr08TADzYhoHm5FgYVR+kgyvPGjhLTeleCznJnGfcXTQ79DEjrbxXXhIlZBAF57bPLsL2kA85TGQx3WfHhWrfSOkp+lw8MKfFI2tHYhjzPDPimB5z+cKmj7u0oxCKLl2m2NrtSaNLVFAnSKKSTaeUfFNnpS/nTj1MHmLnntMomoXNMv7UCoKWWbjFC0I3LzHebNe5ITOd2j22MngIxYfIOiaU2QL/5K7pJOlKsqyb1RSEeNuFezUcZ9v7FE5v1AZx1k22dMwmY8vqamYyO7uOZGS/UCmGtc04/MGiGpo94P40Ogmh5S4CFwYP4O1gh1oQtpSBq9hPkA3b8wJTl9nl+unPsuSEvIhVDg/wMN9RtK9jtSyHl6G7qQ0aJ4t2HINZza1V2oLPZnXwER8jAIJDz5adguniqUrWyA6l/9loiVsbQQUxo1r+pFxQNWiQMPtqMrsDxXEH61RSRAzGRfmY2VxKtCR9QkF4/NDf7xvr2HMxRa+WlTYNEgykAEY0iNstFOYEPc169c=
  app: enigmatic-refuge-40089
  on:
    repo: ispoljari/blog-app-ci
